### ISSUE TITLE
Support shm-size Docker option

### ISSUE THREAD

**Issue by mboudreau** [jenkinsci/amazon-ecs-plugin#107]
Hi,

I've hit this issue trying to do end to end testing with firefox and geckodriver where the browser just crashes because it hit the shm size limit defaulted to 64mb in Docker.  When setting this higher, everything works again.  

The problem, of course, is that this plugin doesn't support that option currently which would make my life infinitely easier.  I'm sure I'm not the only one that's had this issue.

Cheers.

**Comment by webratz** [comment]
Could you maybe add some more details?
Typically this plugin uses a pre-configured ECS cluster (eg via cloudformation or terraform), where all these configurations regarding docker etc are done.
This might be therefore out of scope to what the plugin is doing.

**Comment by mboudreau** [comment]
I don't think so, since it's based on the ECS task definition of how to run the jenkins agent.  

[I created an PR with my changes](https://github.com/jenkinsci/amazon-ecs-plugin/pull/108).  I still need to fully test it out on our production jenkins, but to mitigate risk, it'll only be done after hours.

**Comment by webratz** [comment]
this should be fixed with #108 right?

**Comment by mboudreau** [comment]
Yep :)

**Comment by webratz** [comment]
just released 1.21-beta so you can test it if you want

**Comment by mboudreau** [comment]
Awesome, thanks!

**Comment by mboudreau** [comment]
Looks like it's working on our production as you can see the task definition is set here:
![image](https://user-images.githubusercontent.com/573668/60642156-312cf100-9e72-11e9-9e11-9c6d9333ac73.png)

And how it looks in the product
![image](https://user-images.githubusercontent.com/573668/60642174-430e9400-9e72-11e9-892e-7591c7a5ba7c.png)

However, our tests are still failing sadly, but I don't think it's because of this change not working since we can see it in the config being there for ECS.

**Comment by mboudreau** [comment]
Yeah, this definitely works :)

**Comment by webratz** [comment]
just released 1.21
